Controllers/CategoryController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using EffectiveWebProg.Models;
using EffectiveWebProg.ViewModels;
using EffectiveWebProg.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EffectiveWebProg.Controllers;

public class CategoryController : Controller
{
    private ApplicationDbContext _db;

    public CategoryController(ApplicationDbContext db)
    {
        _db = db;
    }

    public async Task<IActionResult> Index()
    {
        var cat = await _db.ItemCats.ToListAsync();
        return View(cat);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("CatType")] ItemCatModel categoryModel)
    {
        if (ModelState.IsValid)
        {
            categoryModel.CatID = Guid.NewGuid();
            _db.Add(categoryModel);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(categoryModel);
    }

}

Views/Category/Index.cshtml
@model List<EffectiveWebProg.Models.ItemCatModel>

@{
    ViewData["Title"] = "Category Page";
}

<h2>Categories</h2>

<br>
<div class="row">
    <div class="col-md-12">
        <a asp-action="Create" asp-controller="Category" class="btn btn-success">Create New Category</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Category ID</th>
                    <th>Category Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.CatID</td>
                        <td>@item.CatName</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>