Controllers/ItemCatController.cs
using Microsoft.AspNetCore.Mvc;
using EffectiveWebProg.Models;
using EffectiveWebProg.Data;
using Microsoft.EntityFrameworkCore;

namespace EffectiveWebProg.Controllers;

public class ItemCatController : BaseController
{
    private ApplicationDbContext _db;

    public ItemCatController(ApplicationDbContext db)
    {
        _db = db;
    }

    public async Task<IActionResult> Index()
    {
        var cat = await _db.ItemCat.ToListAsync();
        return View(cat);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("CatName")] ItemCatModel itemCatModel)
    {
        if (ModelState.IsValid)
        {
            itemCatModel.CatID = Guid.NewGuid();
            _db.Add(itemCatModel);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(itemCatModel);
    }

}

Views/ItemCat/Create.cshtml
@model EffectiveWebProg.Models.ItemCatModel

<h1>Create Category</h1>

<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" method="post">
            <div class="form-group">
                <label asp-for="CatName" class="control-label"></label>
                <input asp-for="CatName" class="form-control" />
                <span asp-validation-for="CatName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/ItemCat/Index.cshtml
@model List<EffectiveWebProg.Models.ItemCatModel>

@{
    ViewData["Title"] = "Item Category Page";
}

<h2>Categories</h2>

<br>
<div class="row">
    <div class="col-md-12">
        <a asp-action="Create" asp-controller="ItemCat" class="btn btn-success">Create New Category</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Category ID</th>
                    <th>Category Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.CatID</td>
                        <td>@item.CatName</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>